### ISSUE TITLE
Метод getAllowableSymbolsLineLength в IPrinterService всегда возвращает 1

### ISSUE THREAD

**Issue by hyperax** [evotor/device-drivers#28]
Воспроизводится на прошивке 2.3.0.0000-0200-002P-00.
Ранее возвращалось значение в соответствии с шириной ленты.

[IPrinterService](https://github.com/evotor/device-drivers/blob/fc0a5802efb2a0c8bfb6420b60acc3916e2fde00/app/src/main/aidl/ru/evotor/devices/commons/IPrinterService.aidl#L13)

**Comment by rMozg** [comment]
Да, спасибо, есть такой баг. Будет исправлен в ближайшее время.
